version: "2"

services:
    #baso_os:
    #    build:
    #        context: ./base_os
    #        dockerfile: Dockerfile
    #    image: base_os:0.2
    potato_suit:
        restart: always
        #build:
        #    context: ./
        #    dockerfile: Dockerfile
        #image: potato:0.8
        image: registry.cn-hangzhou.aliyuncs.com/potato/potato:0.8
        container_name: potato_suit
        hostname: potato_suit
        ports:
            - 5555:5555   #celery-flower
            - 8080:8080   #potato web
            - 8888:8888   #notebook
            - 27017:27017 #mongodb
        volumes:
            - /home/work/project/potato/notebook:/notebook
            - /home/work/project/potato/stratlib:/opt/potato/stratlib
            - /data/mongodb:/var/lib/mongodb           
